server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa


appmsg:
  messages:
   contactsavesuccess : Contact saved.
   contactsavefailed : Contact save failed.
   contactdelsuccess : Record Deleted.
   contactdelfailed : Delete failed.